<program>     ::= <stmt_list> <eof>
<stmt_list>   ::= <stmt> <stmt_list> | ""
<stmt>        ::= <id> ":=" <expr> | "read" <id> | "write" <expr>
<expr>        ::= <term> <term_tail>
<term_tail>   ::= <ao> <term> <term_tail> | ""
<term>        ::= <factor> <fact_tail>
<factor_tail> ::= <mo> <factor> <fact_tail> | ""
<factor>      ::= "(" <expr> ")" | <id> | <i_lit>
<ao>          ::= "+" | "-"
<mo>          ::= "*" | "/"